[WIP]: Update docs on fresher's selection
kossiitkgp/docs pull request #62
Opened 2023-06-10 14:55 UTC by proffapt

**Write path(s) which will be affected by this Pull Request.**
Example:
- `/events/freshers-selection`

**Why do you think it should be documented?**

- Archival of past 2 years FB post.
- Mentioning of `[mailing-scripts](https://github.com/kossiitkgp/mailing-scripts)` for ease in mailing

2023-06-10 16:38 UTC, harshkhandeparkar requested changes
Small change, otherwise LGTM.

2023-06-10 16:38 UTC, harshkhandeparkar commented on events/freshers-selection.md
> +All the mails sent during the selection process are sent via [mailing-scripts](https://github.com/kossiitkgp/mailing-scripts). It already has all of the templates of the mail which are to be sent dur
```suggestion
All the mails sent during the selection process are sent using the [mailing-scripts](https://github.com/kossiitkgp/mailing-scripts). It already has all of the templates of the mail which are to be sent during any round.
```

2023-06-10 20:04 UTC, proffapt commented on events/freshers-selection.md
> +All the mails sent during the selection process are sent via [mailing-scripts](https://github.com/kossiitkgp/mailing-scripts). It already has all of the templates of the mail which are to be sent dur
What difference does it make (*￣▽￣)b

2023-06-11 06:19 UTC, harshkhandeparkar approved these changes
LGTM

2023-06-11 08:00 UTC, rajivharlalka approved these changes

2023-06-11 14:59 UTC, chirag-ghosh approved these changes

2023-06-11 16:28 UTC, proffapt commented
So, can it be merged now?

2023-06-11 18:50 UTC, merged